spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: ${DATASOURCE_URL}
  username: ${DATASOURCE_USERNAME}
  password: ${DATASOURCE_PASSWORD}
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: ${JWT_SECRET_KEY}
  # 30 days
  token.expired-time-ms: 2592000000

spring.redis.url: ${REDIS_URL}


spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username=${CLOUDKARAFKA_USERNAME} password=${CLOUDKARAFKA_PASSWORD};
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: ${BOOTSTRAP_SERVER1}, ${BOOTSTRAP_SERVER2}, ${BOOTSTRAP_SERVER3}
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVER1}, ${BOOTSTRAP_SERVER2}, ${BOOTSTRAP_SERVER3}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      alarm: ${TOPIC_ALARM}
